# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/infrastructure/proto/v1/user/create.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'app/infrastructure/proto/v1/user/create.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.infrastructure.proto.v1.user import model_pb2 as app_dot_infrastructure_dot_proto_dot_v1_dot_user_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-app/infrastructure/proto/v1/user/create.proto\x12\x1cinfrastructure.proto.user.v1\x1a,app/infrastructure/proto/v1/user/model.proto\"K\n\x11\x43reateUserRequest\x12\x36\n\x04user\x18\x01 \x01(\x0b\x32\".infrastructure.proto.user.v1.UserR\x04user\"L\n\x12\x43reateUserResponse\x12\x36\n\x04user\x18\x01 \x01(\x0b\x32\".infrastructure.proto.user.v1.UserR\x04userB\xc2\x01\n com.infrastructure.proto.user.v1B\x0b\x43reateProtoP\x01\xa2\x02\x03IPU\xaa\x02\x1cInfrastructure.Proto.User.V1\xca\x02\x1cInfrastructure\\Proto\\User\\V1\xe2\x02(Infrastructure\\Proto\\User\\V1\\GPBMetadata\xea\x02\x1fInfrastructure::Proto::User::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.infrastructure.proto.v1.user.create_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.infrastructure.proto.user.v1B\013CreateProtoP\001\242\002\003IPU\252\002\034Infrastructure.Proto.User.V1\312\002\034Infrastructure\\Proto\\User\\V1\342\002(Infrastructure\\Proto\\User\\V1\\GPBMetadata\352\002\037Infrastructure::Proto::User::V1'
  _globals['_CREATEUSERREQUEST']._serialized_start=125
  _globals['_CREATEUSERREQUEST']._serialized_end=200
  _globals['_CREATEUSERRESPONSE']._serialized_start=202
  _globals['_CREATEUSERRESPONSE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
