# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/infrastructure/proto/v1/user/service.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'app/infrastructure/proto/v1/user/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.infrastructure.proto.v1.user import create_pb2 as app_dot_infrastructure_dot_proto_dot_v1_dot_user_dot_create__pb2
from app.infrastructure.proto.v1.user import get_pb2 as app_dot_infrastructure_dot_proto_dot_v1_dot_user_dot_get__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.app/infrastructure/proto/v1/user/service.proto\x12\x1cinfrastructure.proto.user.v1\x1a-app/infrastructure/proto/v1/user/create.proto\x1a*app/infrastructure/proto/v1/user/get.proto2\xea\x01\n\x0bUserService\x12q\n\nCreateUser\x12/.infrastructure.proto.user.v1.CreateUserRequest\x1a\x30.infrastructure.proto.user.v1.CreateUserResponse\"\x00\x12h\n\x07GetUser\x12,.infrastructure.proto.user.v1.GetUserRequest\x1a-.infrastructure.proto.user.v1.GetUserResponse\"\x00\x42\xc3\x01\n com.infrastructure.proto.user.v1B\x0cServiceProtoP\x01\xa2\x02\x03IPU\xaa\x02\x1cInfrastructure.Proto.User.V1\xca\x02\x1cInfrastructure\\Proto\\User\\V1\xe2\x02(Infrastructure\\Proto\\User\\V1\\GPBMetadata\xea\x02\x1fInfrastructure::Proto::User::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.infrastructure.proto.v1.user.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.infrastructure.proto.user.v1B\014ServiceProtoP\001\242\002\003IPU\252\002\034Infrastructure.Proto.User.V1\312\002\034Infrastructure\\Proto\\User\\V1\342\002(Infrastructure\\Proto\\User\\V1\\GPBMetadata\352\002\037Infrastructure::Proto::User::V1'
  _globals['_USERSERVICE']._serialized_start=172
  _globals['_USERSERVICE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
