services:
  surrealdb:
    image: surrealdb/surrealdb:v2.2
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    
    ports:
      - 8000:8000
