# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure/proto/v1/health/service.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'infrastructure/proto/v1/health/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,infrastructure/proto/v1/health/service.proto\x12\x1einfrastructure.proto.health.v1\"\x14\n\x12HealthCheckRequest\"G\n\x13HealthCheckResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version2\x82\x01\n\x06Health\x12x\n\x0bHealthCheck\x12\x32.infrastructure.proto.health.v1.HealthCheckRequest\x1a\x33.infrastructure.proto.health.v1.HealthCheckResponse\"\x00\x42\xcd\x01\n\"com.infrastructure.proto.health.v1B\x0cServiceProtoP\x01\xa2\x02\x03IPH\xaa\x02\x1eInfrastructure.Proto.Health.V1\xca\x02\x1eInfrastructure\\Proto\\Health\\V1\xe2\x02*Infrastructure\\Proto\\Health\\V1\\GPBMetadata\xea\x02!Infrastructure::Proto::Health::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructure.proto.v1.health.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.infrastructure.proto.health.v1B\014ServiceProtoP\001\242\002\003IPH\252\002\036Infrastructure.Proto.Health.V1\312\002\036Infrastructure\\Proto\\Health\\V1\342\002*Infrastructure\\Proto\\Health\\V1\\GPBMetadata\352\002!Infrastructure::Proto::Health::V1'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=80
  _globals['_HEALTHCHECKREQUEST']._serialized_end=100
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=102
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=173
  _globals['_HEALTH']._serialized_start=176
  _globals['_HEALTH']._serialized_end=306
# @@protoc_insertion_point(module_scope)
