# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from infrastructure.proto.v1.health import service_pb2 as infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2


class HealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/infrastructure.proto.health.v1.Health/HealthCheck',
                request_serializer=infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2.HealthCheckRequest.FromString,
                    response_serializer=infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infrastructure.proto.health.v1.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infrastructure.proto.health.v1.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infrastructure.proto.health.v1.Health/HealthCheck',
            infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2.HealthCheckRequest.SerializeToString,
            infrastructure_dot_proto_dot_v1_dot_health_dot_service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
